### ISSUE TITLE
treetime: error: too few arguments

### ISSUE THREAD

**Issue by r0sies** [neherlab/treetime#106]
Hi,

I am receiving this error when running treetime.

metadata=st239.metadata.tsv
aln=alignment.filtered_polymorphic_sites.fasta
tree=alignment.final_tree.nwk
module load python/3.6.5
treetime --tree ${tree} --aln ${aln} --dates ${metadata}

usage: TreeTime: Maximum Likelihood Phylodynamics
treetime: error: too few arguments

treetime --version
treetime 0.7.3

input data abbreviated below:
head $metadata
name	date
1	2012.43
2	2012.43
3	2012.55

head $aln
>1
GCGAGGGTTGAGCGGCTTGGGACCGAACAACGCTGAATCCCTTGTGGGGCCTCCCGCATCCGCGGATAGAGGATCACGGCGCCAACACTGGGAAGCTCTGGCTTGATGATTCCGACACCTGAAATGGAAG
..
>10
GCGAGGGTTGAGCGGCTTGGGACCGAACAGCGCTGAATCCCTTGTGGGGCCTCCCGCATCCGAGGATAGAGGATCACGGCGCCAACACTGGAAAGCTCCGGCTTGATGATTCCGACACCTGAAATGGAAA...

head $tree
(((70:13.297602,((64:22.415506,8:27.633684):0.409884,(2:5.034209,36:3.025597):29.162792):1.024431):0.000772,((((97:1.008812,
..

Thank you!

**Comment by r0sies** [comment]
I got the same error with your ebola example dataset: https://github.com/neherlab/treetime_examples/tree/master/data/ebola

**Comment by rneher** [comment]
strange. this works for me in version 0.7.3. Strain names that are just numbers could cause issues though...

```
\:> treetime version
treetime 0.7.4
(base) ran13:/home/richard/Projects/treetime/treetime_examples/data/ebola
\:> treetime --tree ebola.nwk --aln ebola.fasta --dates ebola.metadata.csv 

Attempting to parse dates...
	Using column 'name' as name. This needs match the taxon names in the tree!!
	Using column 'date' as date.

0.00	-TreeAnc: set-up
[...]
````

**Comment by rneher** [comment]
closing this now -- please reopen if this persists.
