### ISSUE TITLE
How to measure reliability when results are unstable？

### ISSUE THREAD

**Issue by xinkwu** [neherlab/treetime#107]
Hi Richard,

When I use treetime to infer the evolution relationship of virus sequences, I find that the results of multiple runs are quite different.
Here are the real running results for 8 times [the R squares are shown here: 0.29, 0.28, 0.28, 0.27, 0.28, 0.28, 0.26, 0.28], and the topology of **timetree.nexus** is different each time.

1. Is this result due to too similar sequences between viruses? How do I measure the reliability of the results? Is it possible to filter the R square of the results of multiple runs and choose the highest one as the final result?

2. Does the selective deletion of some sequences help improve the reliability of the results? Some samples may have problems such as repeated sampling leading to sequence redundancy, some may lack date information, some sequences may be of poor quality, and so on.

Here is the command I run TreeTime:
`treetime --aln virus.fasta --tree virus.nwk --dates metadata.csv --gtr infer --reroot best --covariation --confidence --reconstruct-tip-states --max-iter 10 --outdir resultTreetime`

Any helpful answers are welcome.

Kai

**Comment by rneher** [comment]
the variability here likely comes from random assignment of mutations to branches on either side of the root. Randomness can also arise when your tree has polytomies that are resolved by treetime and there are equal possibilities. If you send me the data, I'd be happy to have a look.
