### ISSUE TITLE
Treetime mugration removes trait comments from timetree. 

### ISSUE THREAD

**Issue by m-a-martin** [neherlab/treetime#114]
When doing both dating of a divergence tree as well as ancestral state reconstruction of a given discrete character, I presume the best workflow is to first run treetime to get the dated tree and then run treetime mugration on the time tree. If it's possible to do both steps in a single analysis, that would be great. Otherwise, I've noticed that the tree which is produced by treetime mugration does not retain the traits (specifically &mutations and &date in my case) comments for each tip/node in the timetree. Thanks for the great program!

**Comment by rneher** [comment]
yes, you would have to run timetree inference first and then mugration on the same tree. But topology and node labeling should not change in mugration. so you should be able to match the nodes and merge the comments. 

if you wrote your analysis in python instead of using the commandline interface, you could do this all in one step.

**Comment by Chjulian** [comment]
I related follow-up question question @rneher. I am interested in run mugration while keeping input branch lengths.  --branch-length-mode does not seem to be working with mugration. Is this expected?

--



--

**Comment by rneher** [comment]
@Chjulian just doing mugration shouldn't touch the branch lengths at all...

**Comment by m-a-martin** [comment]
Similar question -- do the branch lengths affect the mugration inference? In other words will a tree with branch lengths in unit time provide different mugration estimates than a tree with branch length in units of substitutions per site? I imagine it would affect the GTR rates but not the inference?

**Comment by rneher** [comment]
the units shouldn't affect the inference (up to some small number cut-offs). But the rate of the resulting GTR model would be different.

**Comment by m-a-martin** [comment]
Thank you!
