### ISSUE TITLE
error with treetime when running a nextstrain build

### ISSUE THREAD

**Issue by pauloluniyi** [neherlab/treetime#118]
@rneher when trying to run a nextstrain build, I'm getting an error message with treetime, "raise UnknownMethodError("TreeTime.run: rate variation for confidence estimation is not available. Either specify it explicitly, or estimate from root-to-tip regression." do you have a fix for this? or suggestions on how to solve it?

**Comment by rneher** [comment]
what version of treetime are running?

**Comment by pauloluniyi** [comment]
0.7.5

**Comment by rneher** [comment]
I need more details... what exactly are you running. are you sure this is TreeTime? this "http://TreeTime.run" seem very weird

**Comment by acegid** [comment]
Attached is the folder of the data I'm trying to run a nextstrain build for.

and this is the error message I get during job 2:

Job 2: 
        Refining tree
          - estimate timetree
          - use opt coalescent timescale
          - estimate marginal node dates
          - fix clock rate at 0.0006
        


        augur refine             --tree results/tree_raw_s.nwk             --alignment results/aligned_s.fasta             --metadata results/metadata_s.tsv             --output-tree results/tree_s.nwk             --output-node-data results/branch_lengths_s.json             --timetree             --coalescent opt             --clock-rate 0.0006             --date-confidence             --date-inference marginal
        

1.08	WARNING: Previous versions of TreeTime (<0.7.0) RECONSTRUCTED sequences of
    	tips at positions with AMBIGUOUS bases. This resulted in unexpected
    	behavior is some cases and is no longer done by default. If you want to
    	replace those ambiguous sites with their most likely state, rerun with
    	`reconstruct_tip_states=True` or `--reconstruct-tip-states`.

4.10	TreeTime.reroot: with method or node: least-squares

4.10	TreeTime.reroot: rerooting will account for covariance and shared ancestry.

5.92	###TreeTime.run: INITIAL ROUND

28.85	TreeTime.reroot: with method or node: least-squares

28.86	TreeTime.reroot: rerooting will account for covariance and shared
     	ancestry.

29.51	###TreeTime.run: rerunning timetree after rerooting

55.99	###TreeTime.run: ITERATION 1 out of 2 iterations

95.23	###TreeTime.run: ITERATION 2 out of 2 iterations
Traceback (most recent call last):
  File "/Users/Paulsons/.conda/envs/nextstrain/bin/augur", line 8, in <module>
    sys.exit(main())
  File "/Users/Paulsons/.conda/envs/nextstrain/lib/python3.6/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/Users/Paulsons/.conda/envs/nextstrain/lib/python3.6/site-packages/augur/__init__.py", line 74, in run
    return args.__command__.run(args)
  File "/Users/Paulsons/.conda/envs/nextstrain/lib/python3.6/site-packages/augur/refine.py", line 203, in run
    covariance=args.covariance, resolve_polytomies=(not args.keep_polytomies))
  File "/Users/Paulsons/.conda/envs/nextstrain/lib/python3.6/site-packages/augur/refine.py", line 70, in refine
    vary_rate=vary_rate, use_covariation=covariance, **kwarks)
  File "/Users/Paulsons/.conda/envs/nextstrain/lib/python3.6/site-packages/treetime/treetime.py", line 249, in run
    raise UnknownMethodError("TreeTime.run: rate variation for confidence estimation is not available. Either specify it explicitly, or estimate from root-to-tip regression.")
treetime.UnknownMethodError: TreeTime.run: rate variation for confidence estimation is not available. Either specify it explicitly, or estimate from root-to-tip regression.


[lassa_nig.zip](https://github.com/neherlab/treetime/files/4580722/lassa_nig.zip)

**Comment by pauloluniyi** [comment]
Attached is a folder of the data I'm trying to run a nextstrain build for:

[lassa_nig.zip](https://github.com/neherlab/treetime/files/4580739/lassa_nig.zip)

and this is the error message it's running job 2 from the nextstrain conda environment:

Job 2: 
        Refining tree
          - estimate timetree
          - use opt coalescent timescale
          - estimate marginal node dates
          - fix clock rate at 0.0006
        


        augur refine             --tree results/tree_raw_s.nwk             --alignment results/aligned_s.fasta             --metadata results/metadata_s.tsv             --output-tree results/tree_s.nwk             --output-node-data results/branch_lengths_s.json             --timetree             --coalescent opt             --clock-rate 0.0006             --date-confidence             --date-inference marginal
        

1.08	WARNING: Previous versions of TreeTime (<0.7.0) RECONSTRUCTED sequences of
    	tips at positions with AMBIGUOUS bases. This resulted in unexpected
    	behavior is some cases and is no longer done by default. If you want to
    	replace those ambiguous sites with their most likely state, rerun with
    	`reconstruct_tip_states=True` or `--reconstruct-tip-states`.

4.10	TreeTime.reroot: with method or node: least-squares

4.10	TreeTime.reroot: rerooting will account for covariance and shared ancestry.

5.92	###TreeTime.run: INITIAL ROUND

28.85	TreeTime.reroot: with method or node: least-squares

28.86	TreeTime.reroot: rerooting will account for covariance and shared
     	ancestry.

29.51	###TreeTime.run: rerunning timetree after rerooting

55.99	###TreeTime.run: ITERATION 1 out of 2 iterations

95.23	###TreeTime.run: ITERATION 2 out of 2 iterations
Traceback (most recent call last):
  File "/Users/Paulsons/.conda/envs/nextstrain/bin/augur", line 8, in <module>
    sys.exit(main())
  File "/Users/Paulsons/.conda/envs/nextstrain/lib/python3.6/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/Users/Paulsons/.conda/envs/nextstrain/lib/python3.6/site-packages/augur/__init__.py", line 74, in run
    return args.__command__.run(args)
  File "/Users/Paulsons/.conda/envs/nextstrain/lib/python3.6/site-packages/augur/refine.py", line 203, in run
    covariance=args.covariance, resolve_polytomies=(not args.keep_polytomies))
  File "/Users/Paulsons/.conda/envs/nextstrain/lib/python3.6/site-packages/augur/refine.py", line 70, in refine
    vary_rate=vary_rate, use_covariation=covariance, **kwarks)
  File "/Users/Paulsons/.conda/envs/nextstrain/lib/python3.6/site-packages/treetime/treetime.py", line 249, in run
    raise UnknownMethodError("TreeTime.run: rate variation for confidence estimation is not available. Either specify it explicitly, or estimate from root-to-tip regression.")
treetime.UnknownMethodError: TreeTime.run: rate variation for confidence estimation is not available. Either specify it explicitly, or estimate from root-to-tip regression.

**Comment by rneher** [comment]
I just looked into this... it is actually an augur problem. You are supplying a fixed clock rate and want to calculate confidence intervals. Augur then tells treetime to vary the rate but not by how much. And treetime complains... 

To run this, add `--clock-std-dev 0.0002` (or whatever you think the rate uncertainty is) to the refine command. 

I'll fix it in augur.
