### ISSUE TITLE
Get probability values for ASR

### ISSUE THREAD

**Issue by sokoloko** [neherlab/treetime#119]
Thank you for making available `treetime`. Wondering how to **get probability values for ancestral states** and if less optimal reconstructions can be outputted somehow.

Thanks again,
Sergios

**Comment by rneher** [comment]
are you interested in sequence reconstructions, or discrete trait reconstruction. for the latter, this is possible via

`treetime mugration --confidence ...`

probabilities for regular sequence reconstructions are available if you use treetime in a script and do marginal ancestral inference. each node will have an attribute `marginal_profile` which has the probability of each state.

**Comment by sokoloko** [comment]
Ancestral **sequence** reconstruction, thanks. May I ask for info on said script and marginal anc. inference? Thank you-

**Comment by d-j-e** [comment]
Any chance of same for joint reconstruction - would be handy to be able to check the actual probability that lead to a particular call (indication of support or otherwise for the particular call).

**Comment by rneher** [comment]
For a joint reconstruction, you can't specify the probability of an individual state. Only the most like global configuration is calculated along with its probability.
