### ISSUE TITLE
Discrepancy in root date estimates

### ISSUE THREAD

**Issue by noranekonobokkusu** [neherlab/treetime#123]
Hello,

I am running treetime as follows:
`treetime --aln no_outliers.numbered.al.renamed.fasta --tree no_outliers.numbered.tree.nwk --dates no_outliers.full_dates.tsv --keep-root --clock-filter 4 --clock-rate 0.0008 --clock-std-dev 0.0004
`
(I'm running treetime on covid data so I'm using the parameters mentioned at github.com/nextstrain/ncov/)
The output directory contains two pdf files. root_to_tip_regression.pdf says the date of the root is 2019.9 while treetime.pdf says it is somewhere before 2019 (and the file dates.tsv also contains pretty old dates for some internal nodes). I would expect the dates in two output pdf files to agree with each other. Am I missing something?

Thanks,
Ksenia

**Comment by rneher** [comment]
The root-to-tip regression is an early output of the pipeline. It looks like something went wrong in the later parts. hard to say exactly what happened. How is your tree rooted?

**Comment by noranekonobokkusu** [comment]
My tree is rooted by Wuhan-Hu-1/2019 (EPI_ISL_402125). When I'm adding --coalescent const option, it results in the same root-to-tip plot but the treetime tree now coalesces to 2019-12-09 because the deepest branches become much shorter.

**Comment by rneher** [comment]
yes, this is expected. The coalescent tree prior doesn't affect the root-to-tip plot. But it does affect the other estimations in treetime an in particular will short many branches.

**Comment by noranekonobokkusu** [comment]
but as I understand, without the '--coalescent' option, I'm not adding the coalescent tree prior to the tree. Adding it produces less diverging date estimates between the root-to-tip regression and the dates on treetime. My initial concern was why what treetime produces at the end without the '--coalescent' option differs that much from the root-to-tip regression.

**Comment by rneher** [comment]
Without the coalescent prior, the large number of identical sequences will push the root back when being resolved. This is expected.
