### ISSUE TITLE
Error about  Matplotlib

### ISSUE THREAD

**Issue by hgwu80** [neherlab/treetime#126]
Hi,
My operating system is Ubuntu 18.04.4 LTS. Python: 3.6.9
I installed the treetime from source based on the instruction (https://treetime.readthedocs.io/en/latest/installation.html).
I got some results, but got a warning also. I googled, and try to fix this warning (https://stackoverflow.com/questions/56656777/userwarning-matplotlib-is-currently-using-agg-which-is-a-non-gui-backend-so), but failed. I'm not familar to python.
I would like to know if you can help me to solve the problem below. Any help will be appreciated.
Thanks,
Huiguang

home/huiguang/.local/lib/python3.6/site-packages/Bio/Phylo/_utils.py:642: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
--- saved tree as
     ./h3n2_timetree/timetree.pdf

--- root-to-tip plot saved to 
    ./h3n2_timetree/root_to_tip_regression.pdf

--- alignment including ancestral nodes saved as 
     ./h3n2_timetree/ancestral_sequences.fasta

--- saved divergence times in
     ./h3n2_timetree/dates.tsv

--- tree saved in nexus format as 
     ./h3n2_timetree/timetree.nexus

--- divergence tree saved in nexus format as 
     ./h3n2_timetree/divergence_tree.nexus

**Comment by rneher** [comment]
what exactly where you running? This has to do with whether you are using interactive or non-interactive backends.
