### ISSUE TITLE
Relationship "treetime" and "augur tree"

### ISSUE THREAD

**Issue by phiweger** [neherlab/treetime#133]
Are these two interchangeable, ie do they use the same codebase @rneher ?

**Comment by phiweger** [comment]
> Now we’ll use the topology from tree, but get more accurate branch lengths and a time-resolved tree. This adjusts branch lengths in the tree to position tips by their sample date and infer the most likely time of their ancestors, using TreeTime. There are many options that can be specified here in refine to help you get a good tree. -- https://docs.nextstrain.org/projects/augur/en/stable/tutorials/tb_tutorial.html

Ah, so "augur refine" == "treetime"?

**Comment by emmahodcroft** [comment]
`augur refine` uses `Treetime`, so they are largely interchangeable. Of course, we use Treetime in a very specific way within `augur` - it can be used more flexibly, so if you were to run Treetime under different settings, they might not be 'interchangeable'. I hope that makes sense!

**Comment by phiweger** [comment]
Ah perfectly, thank you! I was wondering, bc/ augur has a `--treetime` flag that has to be set explicitly to turn on treetime.
