### ISSUE TITLE
How to do with the unknown date

### ISSUE THREAD

**Issue by Jinglu1982** [neherlab/treetime#135]
Hi all,

for samples with unknown date we can use like 2020-XX-XX in augur commond, but how can I treat this in treetime? it seems not work in treetime. Many thanks.

Jing

**Comment by ammaraziz** [comment]
You can convert to Year.Fraction. There are a few utility functions in `TreeTime`. You can also continue to use `augur` pipeline, the `refine` subcommand will run treetime and handle ambiguous dates for you.

However, treetime does handle ambiguous dates. Make sure your metadata file has correctly formatted date column. It should be `%Y-%m-%d` which is YYYY-MM-DD or 2017-12-01 (I think the documentation has a type in it, so it's not `%s`)

**Comment by rneher** [comment]
thanks for chiming in @ammaraziz, I fixed the typo! And yes, `treetime` should handle ambiguous dates. @Jinglu1982 please give a more specific example on how this fails so that I can investigate.
