### ISSUE TITLE
treetime not annotating trees

### ISSUE THREAD

**Issue by ramonlorenzo** [neherlab/treetime#136]
Dear  developers,

First of all thank you for this  fantastic tool. I have been using treetime successfully for a while, but lately it has  stopped annotating the output trees with the inferred traits for the  different functionalities. The only difference from my previous analyses  is that I have updated Python to v3.8.5. Could this be the result of  the update or am I doing something else  wrong?
Thank you  very  much in advance!!

**Comment by rneher** [comment]
could you tell me what biopython version your environment is using? I suspect a problem to be somewhere in how treetime interacts with biopython.

**Comment by rneher** [comment]
it looks like this is a problem with Biopython nexus export. I made an issue. I might try to patch this manually. 

https://github.com/biopython/biopython/issues/3361

**Comment by rneher** [comment]
downgrading biopython to 1.76 should fix it. I'll update the requirements.

**Comment by ramonlorenzo** [comment]
Thank you so much for looking at this! Downgrading works perfectly, so I'll do that in the meantime. Thank you again for your help and for this fantastic tool!
