### ISSUE TITLE
 treetime ancestral cannot annote the mutations in nexus format tree file.

### ISSUE THREAD

**Issue by 544728460** [neherlab/treetime#138]
I downloaded the treetime using "conda install -c bioconda treetime". Then I wanted to use " treetime ancestral --aln alignment_outcome.fasta --tree alignment_outcome.nexus" command to get a tree file with mutation information on nodes like this "A45G,G136T,…,". 

Actually, all the procedures went well without any error. But the outcome tree file I got have no mutation information on any nodes. That's very different with the results I got online (https://treetime.biozentrum.unibas.ch/ancestral/anc_RJKJTEVMVBFE).

Can anyone help with this? Thanks!

**Comment by rneher** [comment]
Could you send me the output of
```
python --version
```
and
```
\:> python
>>> from Bio import __version__
>>> print(__version__)
>>> 

```

**Comment by rneher** [comment]
it looks like this is a problem with Biopython nexus export. I made an issue. I might try to patch this manually. 

https://github.com/biopython/biopython/issues/3361

**Comment by rneher** [comment]
downgrading biopython to 1.76 should fix it. I'll update the requirements.

**Comment by 544728460** [comment]
Thanks so much! The problem has been solved after changing the biopython version.
