### ISSUE TITLE
Dated phylogeny on gapped alignment -- possible?

### ISSUE THREAD

**Issue by phiweger** [neherlab/treetime#139]
Say a have a gapped alignment

```
ATGTAGTC
ATG--GTC
ATG-TG-C
```

Is it possible to use Treetime to construct a dated phylogeny? I would like to not drop columns with a gap.

The use case is that I would like to include pangenome-wide SNVs in an outbreak reconstruction; in this case not all SNV "positions" are present in all genomes, eg those in accessory genes.

Thank you for your help!

**Comment by rneher** [comment]
Yes, treetime should work with gapped alignments. but it will ignore gaps in branch length calculations. You could either mark those missing SNPs with `-` or `N`.

**Comment by phiweger** [comment]
Will Treetime use any "information" from those positions or just ignore them?

**Comment by rneher** [comment]
It will use them in ancestral state reconstruction, but will ignore them in branch length calculations.

**Comment by phiweger** [comment]
perfect, thanks a lot!
