### ISSUE TITLE
homoplasy error

### ISSUE THREAD

**Issue by ahmedmagds** [neherlab/treetime#144]
I keep getting the error below. Any clue?
treetime homoplasy --aln homoplasy_25807.fna --tree Multifasta_25807_aligned_.nwk --verbose 6

0.00	-TreeAnc: set-up
read alignment from file homoplasy_25807.fna with 25807 sequences of length 70
read tree from file Multifasta_25807_aligned_.nwk with 25807 leaves

inferring ancestral sequences...

230.80	WARNING: Previous versions of TreeTime (<0.7.0) RECONSTRUCTED sequences
      	of tips at positions with AMBIGUOUS bases. This resulted in unexpected
      	behavior is some cases and is no longer done by default. If you want to
      	replace those ambiguous sites with their most likely state, rerun with
      	`reconstruct_tip_states=True` or `--reconstruct-tip-states`.
...done.

The TOTAL tree length is 7.131e-01 and 2000 mutations were observed.
Of these 2000 mutations,
	 - 31 occur 1 times
	 - 12 occur 2 times
	 - 8 occur 3 times
	 - 4 occur 4 times
	 - 6 occur 5 times
	 - 6 occur 6 times
	 - 5 occur 7 times
	 - 9 occur 8 times
	 - 5 occur 9 times
	 - 3 occur 10 times
	 - 3 occur 11 times
	 - 1 occur 12 times
	 - 1 occur 13 times
	 - 1 occur 15 times
	 - 6 occur 16 times
	 - 2 occur 18 times
	 - 2 occur 19 times
	 - 1 occur 21 times
	 - 1 occur 22 times
	 - 2 occur 24 times
	 - 1 occur 26 times
	 - 2 occur 27 times
	 - 1 occur 28 times
	 - 1 occur 30 times
	 - 2 occur 33 times
	 - 1 occur 34 times
	 - 1 occur 35 times
	 - 1 occur 37 times
	 - 1 occur 44 times
	 - 1 occur 73 times
	 - 1 occur 81 times
	 - 1 occur 82 times
	 - 1 occur 128 times
	 - 1 occur 149 times
	 - 1 occur 175 times
	 - 1 occur 281 times

Of the 70 positions in the genome,
	 - -1 were hit 0 times (expected 0.00)
	 - 8 were hit 1 times (expected 0.00)
	 - 6 were hit 2 times (expected 0.00)
	 - 3 were hit 3 times (expected 0.00)
	 - 3 were hit 4 times (expected 0.00)
	 - 1 were hit 5 times (expected 0.00)
	 - 6 were hit 6 times (expected 0.00)
	 - 4 were hit 7 times (expected 0.00)
	 - 2 were hit 8 times (expected 0.00)
	 - 1 were hit 9 times (expected 0.00)
	 - 4 were hit 10 times (expected 0.00)
	 - 2 were hit 11 times (expected 0.01)
	 - 3 were hit 12 times (expected 0.02)
	 - 3 were hit 15 times (expected 0.14)
	 - 1 were hit 20 times (expected 1.48)
	 - 1 were hit 21 times (expected 2.01)
	 - 1 were hit 23 times (expected 3.24)
	 - 1 were hit 24 times (expected 3.86)
	 - 2 were hit 25 times (expected 4.41)
	 - 1 were hit 27 times (expected 5.13)
	 - 1 were hit 31 times (expected 4.52)
	 - 1 were hit 33 times (expected 3.50)
	 - 1 were hit 34 times (expected 2.94)
	 - 2 were hit 35 times (expected 2.40)
	 - 1 were hit 38 times (expected 1.11)
	 - 1 were hit 40 times (expected 0.58)
	 - 1 were hit 43 times (expected 0.18)
	 - 1 were hit 44 times (expected 0.12)
	 - 1 were hit 45 times (expected 0.08)
	 - 1 were hit 52 times (expected 0.00)
	 - 1 were hit 61 times (expected 0.00)
	 - 1 were hit 63 times (expected 0.00)
	 - 1 were hit 115 times (expected 0.00)
	 - 1 were hit 257 times (expected 0.00)
	 - 1 were hit 277 times (expected 0.00)
	 - 1 were hit 354 times (expected 0.00)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/treetime", line 13, in <module>
    return_code = params.func(params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/treetime/wrappers.py", line 403, in scan_homoplasies
    + np.sum(multiplicities_positions*np.log(p[:len(multiplicities_positions)]+1e-100))))
ValueError: operands could not be broadcast together with shapes (355,) (80,)

**Comment by ahmedmagds** [comment]
@rneher

**Comment by rneher** [comment]
Thanks for flagging this. This is indeed a problem in the homoplasy script that occurs when one site is mutated very often. I just pushed a commit that should fix it. 
https://github.com/neherlab/treetime/commit/f53f678a487ac5efa803bb39386b62260f1195f2
