### ISSUE TITLE
Feature: tracelog

### ISSUE THREAD

**Issue by ktmeaton** [neherlab/treetime#148]
I'd like to propose (and implement) a new feature: a tracelog for timetree runs.

**Problem**: I'd like to troubleshoot why a run is not converging, or compare different runs.
**Solution**: Store run parameters during each iteration and save to a tracelog file.

I wrote a function that stores likelihoods and other parameters for each iteration of the ```TimeTree.run``` function. The output can be visualized with ```Tracer``` for a comparable approach to BEAST/MCMC.

Example: Observing sequence changes and polytomy resolution
![image](https://user-images.githubusercontent.com/14981272/114198966-e337fd80-9921-11eb-9a30-1d18315670ba.png)

Would this be useful/interesting for the treetime community? If so, I could update my fork and start a pull request.

Thanks!
Katherine

**Comment by rneher** [comment]
thanks @ktmeaton for suggestion this. This could be quite useful in some applications! I'd be great if you could take a stab at it!
