### ISSUE TITLE
augur refine prunes out high-quality sequences that were previously retained in other Nextstrain builds

### ISSUE THREAD

**Issue by matt-sd-watson** [neherlab/treetime#154]
Hello, 
Our group maintains a weekly Nextstrain build of 5000 randomly selected ncov sequences. Recently, we experienced odd behaviour during augur refine when 3 of our sequences were pruned out. We had previously not seen this for any of our sequences, as we maintain the policy of including only sequences over 90% completeness and little to no ambiguity. What is further curious is that 2 of these sequences have been included in many previous builds where they were not pruned (these are sequences 1 and 2, sequence 3 has been recently added to the sample pool). 

The 3 sequences are attached with de-identified names to maintain privacy. The collection times, pangolin v2.4.2 and Nextstrain lineages are listed below for each sample (no day is included due to privacy policy): 

sequence_1: November 2020, 20A, B.1.36.38
sequence_2: November 2020, 20B, B.1.1.368
sequence_3: April 2021, 21A, B.1.617.2

Our augur refine parameters are as follows and have been consistent for all previous Nextstrain builds: 

 --timetree \
  --coalescent opt \
  --date-confidence \
  --date-inference marginal \
  --clock-filter-iqd 4 \
  --keep-root

Do you have any intuition as to why these 3 samples would be pruned by augur refine in a particular instance, but not another? I understand that the TreeTime model will remove outliers based on the root-to-tip model and a threshold for deviation from specified interquartile ranges, but I can't seem to find any particular reason why they would be pruned in a specific build and retained in another. Given that we use a substantial number of samples for each build (5000), I can't see how certain samples would have such an influence over the behaviour of the model. 

[augur_refine_pruned_seqs.txt](https://github.com/neherlab/treetime/files/6592996/augur_refine_pruned_seqs.txt)

**Comment by rneher** [comment]
hi @matt-sd-watson 

If these sequences are completely excluded from the build, they must have been flagged at this stage here

https://github.com/nextstrain/augur/blob/master/augur/refine.py#L42-L48

this could have happened either because they are too far from the clock (but as you say, these sequences seems fine), or because they are missing dates, or a different bug. 

do you happen to have the output of the refine command?
