### ISSUE TITLE
Treetime warning - aa_models.py:88

### ISSUE THREAD

**Issue by mstagliamonte** [neherlab/treetime#155]
Hi,

Thank you for making Treetime available; it looks like a great tool and I am trying to move my first steps with it.

I am running treetime v0.7.5 on a computer cluster; the program seems to run fine, and I am getting results; however, at the very start of the log file I get:

```
/apps/treetime/0.7.5/lib/python3.9/site-packages/treetime/aa_models.py:88: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  _BLOSUM45 = np.array([

```

Here is my command   :

```
treetime --tree myTree.nwk \
    --aln myAln.fa \
    --dates myMeta.csv \
    --keep-root --clock-rate 0.0009 --coalescent skyline
```

I was wondering on the origin of the warning. I am not sure if it depends on the python version, or installation, and if I can safely ignore it. I am not trying to use any amino acid model, since I have a nucleotide alignment.

Looking forward to hearing from you,

Max

**Comment by rneher** [comment]
I think this was fixed a while ago. could you check whether this error is still present in later versions?

**Comment by mstagliamonte** [comment]
Thank you for your kind answer. I am using it on a computer cluster, I will ask the admin to install the new version and report back.

Best,
Max

**Comment by mstagliamonte** [comment]
Hi, @rneher  ,

I have just run the version 0.8.1, and the warning is gone. Thank you for your kind help in solving the issue.

Best,
Max
