### ISSUE TITLE
Rounding of dates in skyline.tsv

### ISSUE THREAD

**Issue by mstagliamonte** [neherlab/treetime#156]
HI,

I was looking at the skyline.tsv output, and I noticed that the dates are rounded to the first decimal. This leads to several datapoints having the same date, which prevents me from using the table in custom plots. Is there a way to increase the number of decimals in the output table? Unless I am misunderstanding the output file.

Best,
Max

**Comment by rneher** [comment]
this is currently hard coded here:

https://github.com/neherlab/treetime/blob/master/treetime/wrappers.py#L252

but would be a simple matter of changing the string formating. You can do this locally in your copy if you need a quick fix. I'll try to get this into the next release.

**Comment by mstagliamonte** [comment]
Thank you, I will!

Best,
Max

**Comment by mstagliamonte** [comment]
Hi, @rneher ,

I have just run Treetime with the modified script, and the dates now are reported to an adequate decimal point (3rd decimal point allows to discern a 1 day difference). Thank you for your kind help.

Best,
Max

**Comment by rneher** [comment]
I made a new release that should fix this. thanks for bringing it up!

**Comment by mstagliamonte** [comment]
Great, thank you for being so responsive!

Best,
Max
