### ISSUE TITLE
Output differences (divergence vs. timetree.nexus)

### ISSUE THREAD

**Issue by evandiego83** [neherlab/treetime#158]
Hi Richard,

Many apologies if this is mentioned somewhere in the documentation but I would like to know what are the output differences between the timetree.nexus file and the divergence_tree.nexus. In the divergence nexus file the scale of the first seq i.e. the root is 0 while in the other timetree file the scale is an actual number.

Thanks you
Evan

**Comment by rneher** [comment]
I am not sure I fully understand. In the `timetree.nexus` branch lengths should be measured in years. While in the `divergence_tree.nexus` they are in "expected nucleotide changes per position". The length of the branch leading to the root is arbitrary, as it is connecting to an unknown part of ancestral diversity.

does that make sense?

richard

**Comment by evandiego83** [comment]
thanks you richard. So in the timetree.nexus file as listed below the 0.31128 is a bracnh length with respect to years
Tree tree1=(Wuhan/WH04/2020|2020-01-05:0.31128[&mutations="",date=2020.01] while the other divergence_tree.nexus file 
Tree tree1=(Wuhan/WH04/2020|2020-01-05:0.000000[&mutations="",date=2020.01] indicates 0 change? 

many thanks again.
Evan

**Comment by rneher** [comment]
Yes, there is no mutation on the branch on your divergence tree. Hence the most likely length is 0.
