### ISSUE TITLE
branch lengths for partial sequences (with a lot of NNNNNNNN)

### ISSUE THREAD

**Issue by babarlelephant** [neherlab/treetime#163]
Hi,

I noticed that in this particular case I prefer iqtree's output than augur refine's. This is a SARS-CoV (2003) tree, most sequences are full-length but there are a few spike partial sequences, that I filled with NNNN.

My concern is with the "Hubei civets" clade
https://nextstrain.org/community/babarlelephant/cov/sarscov?branchLabel=none&label=clade:SARS%20early%20phase&m=div
Being spike partial sequences they only have a few mutations, in the spike, separating them from the root of the 2004 civet lineage.

Apparently augur refine only counts those mutations and assigns very short branch lengths to this Hubei civets lineage.

On the other hand iqtree understands that the number of mutations in the spike should be roughly multiplied by 5 to estimate the whole genome divergence and assigns much longer and trustful branch lengths.

**Not sure if I am asking for a fix as iqtree does the job for this particular case, I would be instead asking for insights, as estimating branch lengths of the NNN regions seems to be a complicated problem per se.**

I am not doing anything special to construct the tree

```
iqtree2 -s aligned.fasta -m GTR+G
augur refine --tree aligned.fasta.treefile --alignment aligned.fasta --output-tree tree.nwk --metadata metadata.tsv --timetree --clock-rate 0.0012 --output-node-data branchlengths.json --coalescent "skyline" --date-inference "marginal" --date-confidence
augur export v2 --tree tree.nwk --node-data branchlengths.json --auspice-config auspice_config.json --output cov_sarscov.json --metadata metadata.tsv

```

Thanks a lot.

![image](https://user-images.githubusercontent.com/6537565/137987334-2c8b6453-2539-4646-895e-2365ad131c49.png)

**Comment by rneher** [comment]
thanks for raising this. I see how this would be the result if one uses `--branch-length-inference joint` (which might be what the default `auto` falls back to for your set of sequences). Could you try `--branch-length-inference marginal` and see whether you get longer branches in that case?

**Comment by babarlelephant** [comment]
Dear professor, it worked, thank you.

**Comment by rneher** [comment]
thanks for checking!
