### ISSUE TITLE
Make warning more informative: `Number of tips in tree differs from number of sequences in alignment`

### ISSUE THREAD

**Issue by corneliusroemer** [neherlab/treetime#167]
Add to logging message: number of tips found in tree, number of sequences found in alignment to help debugging in case of mismatch.

https://github.com/neherlab/treetime/blob/f53f678a487ac5efa803bb39386b62260f1195f2/treetime/treeanc.py#L363

**Comment by corneliusroemer** [comment]
Proposal:
```
            self.logger(f"**WARNING: Number of tips in tree ({len(self.tree.get_terminals())}) differs from number of sequences in alignment ({len(self.data.aln)})**", 3, warn=True)
```

**Comment by rneher** [comment]
added to new release
