### ISSUE TITLE
get states of all tips

### ISSUE THREAD

**Issue by antoine4ucsd** [neherlab/treetime#172]
Hello
I ran treetime mugration and get annotated phylogenies with location states. 
I am looking for the equivalent of the getstates function from phytools to summarize/extract the ancestral location of each tip in the output tree. (and ideally some selected tips : e.g. summarize state ancestor of all tips from location A) 
All advices are welcome

thank you!

**Comment by rneher** [comment]
Hi Antoine,

are you using treetime in python as a library, or the command line tool? In the latter case, there should be a tabular output file with all states. there is no straightforward function in the library to do this. but you can access the states as is done here:

https://github.com/neherlab/treetime/blob/master/treetime/wrappers.py#L890

**Comment by antoine4ucsd** [comment]
I am using the cmd line (witihn conda env dedicated to treetime). I will have to look closely into it... I will keep you posted.
thank you!
