### ISSUE TITLE
treetime mugration: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by antoine4ucsd** [neherlab/treetime#173]
Hello
I am trying to run treetime mugration on a large dataset. it usually works well on my laptop so far.
I checked the phylogeny and there is no polytomies. 
after ~1hrs, it seems to work , GTR.txt is written (attached) but I get this error and no annotated tree is written 

```
  File "/martinlab/users/me/miniconda3/envs/treetime_env/lib/python3.9/site-packages/Bio/Phylo/NewickIO.py", line 293, in newickize
    unquoted_label = re.match(token_dict["unquoted node label"], label)
  File "/martinlab/users/me/miniconda3/envs/treetime_env/lib/python3.9/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
  File "/martinlab/users/me/miniconda3/envs/treetime_env/lib/python3.9/re.py", line 291, in _compile
    if isinstance(flags, RegexFlag):
RecursionError: maximum recurs
[GTR.txt](https://github.com/neherlab/treetime/files/7786440/GTR.txt)
ion depth exceeded in __instancecheck__
```

any thoughts?

thank you!

**Comment by antoine4ucsd** [comment]
I am closing it. problem fixed when adding sys.setrecursionlimit(10000) to the treetime file (in the conda env)
Thank you!

**Comment by antoine4ucsd** [comment]
my bad. I was too enthusiast. when increasing the sys.setrecursionlimit in the treetime file , I do get an annotated.nexus output without error but it DOES NOT contain any annotation...
thoughts?

**Comment by rneher** [comment]
it should contain the state of each node as comment in the nexus file. This happens here:

https://github.com/neherlab/treetime/blob/master/treetime/wrappers.py#L900

could you give some more details?

**Comment by rneher** [comment]
@antoine4ucsd, if there is a problem that persists, please let me know and reopen!
