### ISSUE TITLE
write annotated nexus in R?

### ISSUE THREAD

**Issue by antoine4ucsd** [neherlab/treetime#174]
Hello
It sounds stupid but I can't figure out how to keep the node annotation from the mugration nexus output after reading it in R.
I tried something like:
phylotate::write_annotated(tree, filename, format="nexus")
but the node labels are lost.
When doing it manually with figtree (export nexus as currently displayed / inlcude annotation) it works. is there a way to do it in R??
THANK YOU!

**Comment by ammaraziz** [comment]
I think you have to write out the tree file as nhx (nexus extended). Look into `treeio` to write out files. I think `write.beast(nhx)` will do the trick.

**Comment by rneher** [comment]
This doesn't seem like a treetime question. But I am glad it got answered! closing this now.
