### ISSUE TITLE
Negative branch lengths aren't corrected because they are less (more negative) than TINY_NUMBER

### ISSUE THREAD

**Issue by zacmon** [neherlab/treetime#182]
Hi,

I've attached a zipped folder, `wright_fisher_test.zip`, which contains three files that came from a Wright-Fisher simulation. (Not that it matters much, but the passing of a generation is matched to the passing of a day for it to be agreeable with TreeTime's date format, and the tree was created using `raxml-ng` and a Jukes-Cantor model.) I used these inputs and ran TreeTime:

```python
import treetime as tt
ttobj = tt.TreeTime(gtr='Jukes-Cantor', tree='tree.nwk', aln='sequences.fasta', verbose = 0,
                    dates=tt.utils.parse_dates('dates.csv'))
res = ttobj.run(root='best', infer_gtr=True, relaxed_clock=None, max_iter=5, 
                branch_length_mode='marginal', n_iqd=None, resolve_polytomies=None,
                Tc=None, time_marginal="assign", vary_rate=True, sequence_marginal=True)
```

In trying to understand the messaging-passing algorithms, I found that some branch lengths are given values which are smaller than -TINY_NUMBER (-1e-12) provided in `config.py`, so the branch length doesn't get set to 0 [here](https://github.com/neherlab/treetime/blob/7b1ab62a7fe708b75cdc8740bbda8886ea96a2c5/treetime/clock_tree.py#L456-L460). The comment in line 456 says negative branch lengths should never ensue, but I find it happening, well, more than never. I see that negative branch lengths might occur when the number of mutations on a branch is 0. However, what I find puzzling is why aren't negative branch lengths always set to 0 or positive machine precision. 

Could someone explain why branch lengths < -1e-12 don't need to be or aren't corrected for? (E.g., I see branch lengths of -1.000088900582341e-12 which are < than -1e-12.) Is there any harm in setting all negative branch lengths to 0?

Thanks and take good care,
Zach

[wright_fisher_test.zip](https://github.com/neherlab/treetime/files/8137747/wright_fisher_test.zip)

**Comment by rneher** [comment]
thanks for flagging this. I'll have a look. But I think part of the explanation might be that you are using `time_marginal="assign"` which can legitimately result in negative branch lengths.

**Comment by rneher** [comment]
thanks again. this was indeed an issue. Should be fixed with the next release (but this will take a week or two)

**Comment by zacmon** [comment]
Hi,

Thanks for looking into this! To be clear, even with `time_marginal="assign"`, it appeared that `ml_joint` was being run since that was where I was printing the branch lengths to check things. Looking at the code, `time_marginal="assign"` should cause `ml_joint` not to run, correct?

Thanks and take good care,
Zach
