### ISSUE TITLE
CI: Not enough credits to run Travis CI builds

### ISSUE THREAD

**Issue by corneliusroemer** [neherlab/treetime#185]
When looking up why @anna-parker's branch CI checks failed, I noticed we seem to have insufficient credit to run Travis CI builds making it look like commits failed.

https://app.travis-ci.com/github/neherlab/treetime/jobs/567195428#L227

We should probably either disable Travis CI in Github, add credits or move to Github actions based CI.

@ivan-aksamentov @rneher

**Comment by ivan-aksamentov** [comment]
There is enough credits in the org plan right now. Probably a random glitch.

I restarted the job. That won't hurt.

**Comment by ivan-aksamentov** [comment]
Let's discuss CI problems on Slack.
