### ISSUE TITLE
Allowing sub-classes of Bio.Align.MultipleSeqAlignment

### ISSUE THREAD

**Issue by rbturnbull** [neherlab/treetime#194]
Hi,

We are subclassing Bio.Align.MultipleSeqAlignment in our project but when we use an object of our class to do root-to-tip regression using timetree it raises a MissingDataError at line 186 in sequence_data.py. That's because the code doesn't recognize that the alignment is an instance of MultipleSeqAlignment in line 161 which has:
```
        if type(in_aln) is MultipleSeqAlignment:
```
if we change that to:
```
        if isinstance(in_aln, MultipleSeqAlignment):
```

Then it works OK. Would it be possible to make that change? I can submit this as a PR if you are willing.

**Comment by rneher** [comment]
that makes total sense -- thanks for suggesting. I made that change here https://github.com/neherlab/treetime/commit/5010a68546466f2dda0dc600870755f240bda0d9

**Comment by rbturnbull** [comment]
Thanks. That's great!
