### ISSUE TITLE
Reconstruction of ambiguous bases

### ISSUE THREAD

**Issue by jodyphelan** [neherlab/treetime#197]
I noticed a difference in behaviour when reconstructing using vcf or a fasta alignment for ambiguous bases. In the resulting nexus the ambiguous bases in samples are labelled as changes to reference in the branches leading up to the terminal nodes. This does not happen when using the fasta. Is this a know issue?

version = 0.9.0

```
# aln command: 
treetime ancestral --aln core.full.aln --tree core.full.aln.rooted.treefile --outdir aln

#vcf command
treetime ancestral --aln core.vcf --vcf-reference MTB-h37rv_asm19595v2-eg18.fa  --tree core.full.aln.rooted.treefile --outdir vcf
```

**Comment by rneher** [comment]
thanks for flagging this. I have to look into it.

**Comment by jodyphelan** [comment]
Thanks, I've attached a few files that you can use to replicate this.

[example.zip](https://github.com/neherlab/treetime/files/9259036/example.zip)

If you unzip and run the commands from the comment above it will create two output folders - one for aln and one for vcf.
Take a look at position 690465 from the VCF. All samples are alternate except for sample ERR2515186 which has a missing genotype.
```
$ bcftools query -f '[%POS\t%SAMPLE\t%REF\t%ALT\t%GT\n]' core.vcf |  grep 690465
690465	ERR1633824	T	G	1
690465	ERR4553783	T	G	1
690465	ERR2515468	T	G	1
690465	ERR1023439	T	G	1
690465	ERR2512760	T	G	1
690465	ERR2515186	T	G	.
690465	ERR1035040	T	G	1
690465	ERR1023459	T	G	1
690465	ERR2514020	T	G	1
690465	ERR1023512	T	G	1

```

When you grep that position in the nexus file from the aln directory it doesn't appear while it does appear as a G690465T mutation in the branch leading up to ERR2515186 when you use the nexus in the vcf directory.

```
$ grep 690465 aln/annotated_tree\{\}.nexus 

$ grep 690465 vcf/annotated_tree\{\}.nexus 

```
> (ERR2515186:1.30040000e-06[&mutations="C690450A,**G690465T**,G882155A,G1808147A,A2505162G,G2576247A,T3291379A"]

**Comment by rneher** [comment]
thanks! I think I fixed this in https://github.com/neherlab/treetime/commit/7b521242cc1e9d0aca8b3e25f77b84cc14a66498

this had to do with incorrect handling of no-calls in haploid vcfs. I'll make a new release in the next few days.

**Comment by jodyphelan** [comment]
Ah amazing, thanks for the fix and an great tool!
