### ISSUE TITLE
Generation per year assumption in coalescent model?

### ISSUE THREAD

**Issue by mwersebe** [neherlab/treetime#210]
Hi! 

I have a quick question regarding the generations assumptions of the skyline analysis. In the output (to the screen and in the skyline.tsv file) the program assumes 50 generations per year. I was wondering if this assumption can be explicitly changed? I do not see a command line option to edit this. 

Many thanks!

**Comment by anna-parker** [comment]
Hi @mwersebe this can be changed but sadly we have not implemented this option via the command line (yet). We can add this as a feature but if you need to change it quickly you can do that in a python script. The function that calculates the skyline has an option for generation number the `gen` parameter - you can set this to your desired generation number e.g. `skyline_inferred(self, gen=desired_generation_number)`. You can look at `print_save_plot_skyline()` to see how this has been done in the default case. The docs have example scripts for running TreeTime: https://github.com/neherlab/treetime#example-scripts

**Comment by rneher** [comment]
fixed in #211, thanks @anna-parker
