### ISSUE TITLE
"killed" error

### ISSUE THREAD

**Issue by Jadelrea** [neherlab/treetime#217]
Hello,

I am trying to run treetime ancestral:

`treetime ancestral --aln myalignment.fasta --tree mytree.nwk --outdir myancestral`

For a small alignment of 100 samples it works perfectly, however, when I try to run it on am alignment of ~30,000 samples ~1.5Mb length, I get the error "killed" after a couple of hours, without any other output. My guess this is something related to exceeding my RAM? I work on a CentOS, with 32 cpu and 500Gb RAM.

This is the messege:
0.00	-TreeAnc: set-up
killed

I guess my question would be: is there any estimated maximum number of samples of a given length I can imput treetime based on my RAM? or can my problem be due to any other reason?

**Comment by anna-parker** [comment]
Hi @Jadelrea could you perhaps run this command with higher verbosity (e.g. 6) so that we might get more information on where it fails?

**Comment by Jadelrea** [comment]
Hi @anna-parker, 
Thank you for your answer. I forgot to say I've already tried that, but the error report is exactly the same.

**Comment by rneher** [comment]
I am afraid this won't work. TreeTime is not optimized for long sequences and will use way too much memory in this case.
