### ISSUE TITLE
IndexError in vcf_utils.py

### ISSUE THREAD

**Issue by andreott** [neherlab/treetime#218]
This code fragment generates an index error if there is a mutation entry for the last sequence position as it does not check before using index `pi+1`

https://github.com/neherlab/treetime/blob/a27cc685a89f9e0cb3b2d9608d82de3f1e48ae1d/treetime/vcf_utils.py#L429-L438

As a potential lazy fix you could add another except:

```python
for k,v in sequences.items(): 
     try: 
         pattern.append(sequences[k][pi]) 
     except KeyError: 
         pattern.append(ref[pi]) 
  
     try: 
         pattern2.append(sequences[k][pi+1]) 
     except KeyError:
         try:
             pattern2.append(ref[pi+1]) 
         except IndexError:
             pass
```    

I can also prepare a pull request if you like

**Comment by anna-parker** [comment]
Hi @theosanderson thank you very much for pointing out this issue and suggesting a way to fix it! No need to prepare a PR we can do that :-)
