### ISSUE TITLE
tt.optimize_tree throws `IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed`

### ISSUE THREAD

**Issue by corneliusroemer** [neherlab/treetime#222]
From Dan Lu over at: https://discussion.nextstrain.org/t/indexerror-too-many-indices-for-array-array-is-1-dimensional-but-2-were-indexed/1294

> Has anyone seen this error before? I don’t have enough Treetime or Python knowledge to dig it TnT This is a build with randomly selected mpox sequences. I’ve seen the same error in step refine instead of fix_tree for other sets of randomly selected sequences.
> 
> I’m trying to understand on a high level what may be the cause. For example, are the samples too diverse, or have too many mutations, or mutations that don’t agree with each other that led to this error? I’m not trying to understand for this specific set of samples which sample broke the run.
> 
> Input data can be downloaded here: [debug_data/treetime at main · danrlu/debug_data · GitHub](https://github.com/danrlu/debug_data/tree/main/treetime)
 
![image](https://user-images.githubusercontent.com/25161793/209375062-ec8b2859-45cc-4229-adee-bdcd24648a87.png)

Version:
treetime 0.9.4
[monkeypox/fix_tree.py at 644d07ebe3fa5ded64d27d0964064fb722797c5d · nextstrain/monkeypox · GitHub](https://github.com/nextstrain/monkeypox/blob/644d07ebe3fa5ded64d27d0964064fb722797c5d/scripts/fix_tree.py) (current master branch)

**Comment by danrlu** [comment]
Thanks Cornelius! I think it's a problem from my aligned sequences, not Treetime. Thanks for creating a issue, someone with the same problem can find it easily in the future.

<img width="725" alt="image" src="https://user-images.githubusercontent.com/20667188/209388148-4f5d472e-e641-4abb-a00c-3e4f4445d1f1.png">
