### ISSUE TITLE
In mugration analysis: State of root node is not output to annotated nexus tree (but to CSV when using --confidence)

### ISSUE THREAD

**Issue by agormp** [neherlab/treetime#226]
Playing around with your very useful tool here and hugely enjoying it!

One thing: I notice that if you reconstruct ancestral states using the "mugration" sub-command, then the state of the root node is not output on the annotated ancestral tree. Below is the end of a typical Newick string from a Nexus file output by the mugration command:

`)NODE_0000179:0.00385[&state="Swine"])NODE_0000000:0.00100;`

Note how there is no ancestral state comment listed for `NODE_0000000` (the root of the tree), but there is one for `NODE_0000179`.

If you use the option `--confidence` then you get the values for the possible states of the root node in the resulting CSV file. Below are the top three lines from such a file:

```csv
#name, A, B
NODE_0000000, 0.28847000410188417, 0.7115299958981158
NODE_0000001, 0.28528076828060617, 0.7147192317193939
seq_165, 1.0, 0.0
...
```

Here, the first line shows the confidences in the possible ancestral states of the root node. Incidentally, it would be useful for the headers to be the actual state names instead of A and B.

**Comment by rneher** [comment]
thanks for flagging this. It should be fixed in the latest release!
