### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by yexiao-cheng** [neherlab/treetime#229]
Hi,

There might be a typo in the [Treetime documentation](https://github.com/neherlab/treetime/blob/master/docs/source/tutorials/timetree.rst#vcf-files-as-input).

<img width="851" alt="截屏2023-03-29 17 26 28" src="https://user-images.githubusercontent.com/87927817/228490008-0be79de8-50ba-496e-9209-03c6c5d9e99f.png">

I think it should be:

For many bacterial data set `where` the temporal signal in the data is weak ...

Thanks,

Yexiao

**Comment by corneliusroemer** [comment]
Spot on :)
