### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by tillea** [neherlab/treetime#24]
Hi,
I'm writing you on behalf of the Debian Med team which is a group inside Debian with the objective to package free software in life sciences and medicine for official Debian.  It would be interesting for us to package treetime.  It would help if you could tag your releases to enable us automatically detecting what you consider as user targeting release and any ot such updates.
Thanks for considering, Andreas.

**Comment by rneher** [comment]
just made a first release! thanks for the heads up.

**Comment by tillea** [comment]
On Wed, Jun 21, 2017 at 10:58:15AM -0700, Richard Neher wrote:
> just made a first release! thanks for the heads up.
Thanks.  As promised I'll upgrade the package once it has passed Debian New queue.  Andreas.
