### ISSUE TITLE
Some issues with tests

### ISSUE THREAD

**Issue by tillea** [neherlab/treetime#25]
Hi,
I have packaged treetime for Debian and uploaded it to the new packages queue.  When trying to run the tests I needed to apply some [patches](https://anonscm.debian.org/cgit/debian-med/python-treetime.git/tree/debian/patches/fix_test.patch).  One test does not run anyway

    $ python tree_time_test.py 
    test_aln_to_leaves (__main__.TestTreeAnc) ... ERROR
    test_optimize_ (__main__.TestTreeAnc) ... ok
    test_read_newick (__main__.TestTreeAnc) ... ERROR
    testset_additional_tree_params (__main__.TestTreeAnc) ... ERROR
    
    ======================================================================
    ERROR: test_aln_to_leaves (__main__.TestTreeAnc)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "tree_time_test.py", line 25, in test_aln_to_leaves
        anc_t = treeanc.TreeAnc.from_file(resources_dir+'PR.B.100.nwk', 'newick')
    AttributeError: type object 'TreeAnc' has no attribute 'from_file'
    
    ======================================================================
    ERROR: test_read_newick (__main__.TestTreeAnc)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "tree_time_test.py", line 14, in test_read_newick
        anc_t = treeanc.TreeAnc.from_file(resources_dir+'PR.B.100.nwk', 'newick')
    AttributeError: type object 'TreeAnc' has no attribute 'from_file'
    
    ======================================================================
    ERROR: testset_additional_tree_params (__main__.TestTreeAnc)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "tree_time_test.py", line 19, in testset_additional_tree_params
        anc_t = treeanc.TreeAnc.from_file(resources_dir+'PR.B.100.nwk', 'newick')
    AttributeError: type object 'TreeAnc' has no attribute 'from_file'
    
    ----------------------------------------------------------------------
    Ran 4 tests in 0.000s
    
    FAILED (errors=3)

Kind regards, Andreas.

**Comment by rneher** [comment]
thanks. will look into this.

**Comment by rneher** [comment]
Ok, these were old obsolete tests. I removed them and exposed the nosetests functions via a separate small script.

**Comment by tillea** [comment]
On Mon, Jun 19, 2017 at 07:06:48AM -0700, Richard Neher wrote:
> Ok, these were old obsolete tests. I removed them and exposed the nosetests functions via a separate small script.

Thanks, I'll upload this once treetime was accepted from new queue and update with a new arbitrary version.
