### ISSUE TITLE
Newick formatting error fasttree

### ISSUE THREAD

**Issue by hbarbian** [neherlab/treetime#259]
Hello TreeTime team, 

I am getting a Newick formatting error when running TreeTime with a large dataset.  The tree contains 195,351 SARS-CoV-2 sequences, was built using FastTree, and does contain some identical sequences 

treetime 0.10.1
treetime --tree 230209_wave2_aligned_renamed.nwk --dates 230227_wave2_meta.csv --aln 230209_wave2_aligned_renamed.fasta --outdir timetree

Output:
> 0.00	-TreeAnc: set-up
> TreeAnc: could not load tree, format needs to be nexus or newick! input was 230209_wave2_aligned_renamed.nwk
> Tree loading/building failed.
> No tree -- exiting.

I get more clues when running treetime via Nextstrain augur:
augur 22.0.2
augur refine \
	--tree 230209_wave2_aligned_renamed.nwk \
	--alignment 230209_wave2_aligned_renamed.fasta \
	--metadata 230227_wave2_meta.csv \
	--timetree \
	--output-tree results/230209_wave2_aligned_renamed_timetree.nwk \
	--output-node-data results/branch_lengths.json

Output:
> Building a tree via:
> 	FastTreeMP -nt -nosupport 230209_wave2_aligned_renamed.fasta 1> 230209_wave2_aligned_renamed.nwk 2> 230209_wave2_aligned_renamed.nwk.log
> 	Price et al: FastTree 2 - Approximately Maximum-Likelihood Trees for Large Alignments.
> 	PLoS ONE 5(3): e9490. https://doi.org/10.1371/journal.pone.0009490
> 
> ERROR: TREE BUILDING FAILED
> ERROR: Mismatch, 118994 open vs 118974 close parentheses.
> Please see the log file for more details: 230209_wave2_aligned_renamed.nwk.log
> 
> Building original tree took 156946.6245253086 seconds
> Traceback (most recent call last):
>   File "/home/rushgmcf/.nextstrain/runtimes/conda/env/lib/python3.10/site-packages/augur/__init__.py", line 66, in run
>     return args.__command__.run(args)
>   File "/home/rushgmcf/.nextstrain/runtimes/conda/env/lib/python3.10/site-packages/augur/refine.py", line 160, in run
>     T = read_tree(args.tree)
>   File "/home/rushgmcf/.nextstrain/runtimes/conda/env/lib/python3.10/site-packages/augur/utils.py", line 69, in read_tree
>     T = Bio.Phylo.read(fname, fmt)
>   File "/home/rushgmcf/.nextstrain/runtimes/conda/env/lib/python3.10/site-packages/Bio/Phylo/_io.py", line 60, in read
>     tree = next(tree_gen)
>   File "/home/rushgmcf/.nextstrain/runtimes/conda/env/lib/python3.10/site-packages/Bio/Phylo/_io.py", line 49, in parse
>     yield from getattr(supported_formats[format], "parse")(fp, **kwargs)
>   File "/home/rushgmcf/.nextstrain/runtimes/conda/env/lib/python3.10/site-packages/Bio/Phylo/NewickIO.py", line 125, in parse
>     yield self._parse_tree(buf)
>   File "/home/rushgmcf/.nextstrain/runtimes/conda/env/lib/python3.10/site-packages/Bio/Phylo/NewickIO.py", line 202, in _parse_tree
>     raise NewickError(
> Bio.Phylo.NewickIO.NewickError: Mismatch, 118994 open vs 118974 close parentheses.

What I tried: 
- The input newick file can be read by FigTree. Exporting a Newick or Nexus file from FigTree doesn't solve the issue.
- When I search the newick file, I find 195273 open and 195273 closed parentheses, not 118994 open vs 118974 close parentheses as reported in the error.
- I searched for characters that could affect Newick format in the fasta headers:  parenthesis, commas, square-brackets, colon, semi-colon, and whitespace and didn’t find any.
- I tried running a small subset of the data (first 10 genomes) and it completed TreeTime without error.

Any help would be greatly appreciated!

**Comment by corneliusroemer** [comment]
Thanks for reporting this and all your investigations! It's hard to dig into this without having the tree that's causing the error. Could you either upload it here (might need to change the extension to .txt) or send via email to cornelius.roemer at unibas.ch? That'd be great!

**Comment by corneliusroemer** [comment]
This is unlikely to be a bug in treetime itself - but rather in Biopython, as treetime simply uses Bio.Phylo read:
https://github.com/neherlab/treetime/blob/9fdceaa5157fd0fd4bb141f45e1d742167e5d4c9/treetime/treeanc.py#L307

It just doesn't show the traceback in the way augur does, which uses the same function to load the tree.

You can probably reproduce with:

```py
from Bio import Phylo
Phylo.read(FILENAME, 'newick')
```

There are two options here:
1. Your tree is a correct newick tree and it's a bug in Biopython
2. There's something off with your tree

In either case it's not something that we can fix in treetime - but thanks for reporting anyways, you never know!

Treetime could surface the traceback better.

**Comment by hbarbian** [comment]
Tree attached - thanks for your help! 

[230209_wave2_aligned_renamed_nwk.txt](https://github.com/neherlab/treetime/files/13183141/230209_wave2_aligned_renamed_nwk.txt)

If a Biopython issue, do you think it is related to the large size of the tree, or something about the newick output from fasttree?
