### ISSUE TITLE
ERROR: Cannot read metadata: need at least one column that contains the taxon labels.

### ISSUE THREAD

**Issue by timeresistance1996** [neherlab/treetime#264]
Hi,
    I'm going to use treetime but I run out with this ERROR:

Attempting to parse dates...
Traceback (most recent call last):
  File "/root/anaconda3/bin/treetime", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/lib/python3.8/site-packages/treetime/__main__.py", line 21, in main
    return_code = params.func(params)
  File "/root/anaconda3/lib/python3.8/site-packages/treetime/argument_parser.py", line 237, in toplevel
    timetree(params)
  File "/root/anaconda3/lib/python3.8/site-packages/treetime/wrappers.py", line 306, in timetree
    dates = utils.parse_dates(params.dates, date_col=params.date_column, name_col=params.name_column)
  File "/root/anaconda3/lib/python3.8/site-packages/treetime/utils.py", line 336, in parse_dates
    raise err
  File "/root/anaconda3/lib/python3.8/site-packages/treetime/utils.py", line 285, in parse_dates
    raise MissingDataError("ERROR: Cannot read metadata: need at least one column that contains the taxon labels."
treetime.MissingDataError: ERROR: Cannot read metadata: need at least one column that contains the taxon labels. Looking for the first column that contains 'name', 'strain', or 'accession' in the header.

    This happens also when I test with your test file [ebola] (https://github.com/neherlab/treetime_examples/tree/master/data/ebola).

    How can I deal with it?

**Comment by corneliusroemer** [comment]
Thanks for reporting! I'm happy to help see what's up. Can you share the
full command you used to run on the ebola example that resulted in the
error?

**Comment by timeresistance1996** [comment]
Thank you for your reply!

I was run with "treetime --aln ebola.fasta --tree ebola.nwk --dates ebola.metadata.csv" under the file path.

**Comment by Plasmegnago** [comment]
Hi.
I'm new to Treetime, but I had a similar error. 
I solved it removing the ">" from the ".csv" file.

**Comment by timeresistance1996** [comment]
Hi Plasmegnago，

Thanks for that. But are you certain that there is a ">" in the ".csv" file?

This does not exist in “ebola.metadata.csv” from my observation.

**Comment by Plasmegnago** [comment]
I am sorry. I didn't check the "ebola.metadata.csv", clearly the error is not the same.
I did download the same dataset and try your command "treetime --aln ebola.fasta --tree ebola.nwk --dates ebola.metadata.csv".
It works.
Maybe try to check your ".csv".
When i open it with a text editor (notepad++) it looks like this:
name, date
EM_COY_2015_015982, 2015.30
G3676, 2014.40
EM_COY_2015_015980, 2015.30
G3670, 2014.40
CON-10590, 2015.61
NM042, 2014.42
EM_079497, 2014.26
2507_C2_10080_EMLK, 2015.06
G3677, 2014.40
LIBR10180, 2014.77
KG12, 2015.40
G3770, 2014.44
Makona-G5114.1, 2014.63
EM_COY_2015_023747, 2015.69
EM_FORE_2015_1023, 2015.49
J0170, 2014.86

I hope this will help.

**Comment by rneher** [comment]
@timeresistance1996 and @Plasmegnago 

thanks for using TreeTime!

I ran the command you posted `treetime --aln ebola.fasta --tree ebola.nwk --dates ebola.metadata.csv` in the `ebola` data directory and the command completed without problem. This is on python 3.12 on ubuntu. Do you still have this problem? If so, you provide some more detail?

best,
richard

**Comment by timeresistance1996** [comment]
@rneher and @Plasmegnago，

This is because I copied the wrong delimiter, I have resolved the issue.
 Thank you so mush.
