### ISSUE TITLE
Different output trees

### ISSUE THREAD

**Issue by MarliesJFrancine** [neherlab/treetime#265]
Hi! 

I have a single dataset, and I used it as input in (1) timetree construction, (2) ancestral sequence reconstruction, and (3) mugration analysis. My doubt is why each tree looks very different. The sequences are the same, so my understanding would be that at least the clades of the tree would be similar, but they are not. Can you share some insight on if the trees are constructed in three different ways?

**Comment by rneher** [comment]
The tree might be rooted differently. time tree construction reroots the tree. ancestral reconstruction and mugration should not change the tree other than removing zero length branches (if you don't provide a tree, a tree will be build using fasttree).

**Comment by MarliesJFrancine** [comment]
Thank you! That was indeed the difference :)
