### ISSUE TITLE
How to resolve Polytomies in the tree

### ISSUE THREAD

**Issue by Sikandar37** [neherlab/treetime#266]
Dear All,
I have Constructed a tree using IQtree and dated the tree using Treetime v0.9.0 based on the collection date. I used this script to date the tree
**treetime -- tree tree file --dates metadata.csv --aln sequences.fas --clock-filter 4** 
It worked well and I got the dated tree. My purpose is to use this tree as a fixed tree topology for the beast and one of the requirements for that is tree should be fully bifurcated. so I tried this script to resolve the polytomies. 
**treetime -- tree tree file --dates metadata.csv --aln sequences.fas --clock-filter 4 --stochastic-resolve**
**treetime -- tree tree file --dates metadata.csv --aln sequences.fas --clock-filter 4 --greedy-resolve**
But i am getting an error like unrecognized arguments.; stochastic-resolve 
Is there any solution for this? 
I can do this by R in the ape package 
but I would appreciate if there is a way to resolve polytomies using Treetime.
Thank you

**Comment by rneher** [comment]
excellent!
