### ISSUE TITLE
BUG: clock_filter_method='residuals' should be 'residual'

### ISSUE THREAD

**Issue by zacmon** [neherlab/treetime#267]
Hi,

I'm running TreeTime 0.11.2. There should probably be a check in `TreeTime.clock_filter` that checks the value of `method`:

```python
if method != 'residual' or method != 'local':
    raise ValueError
```

As it stands, the default value given to the clock_filter method is `residuals` which is incompatible with the `clock_filter` method.

Zach

**Comment by rneher** [comment]
thanks for raising this! I pushed a fix!

https://github.com/neherlab/treetime/commit/624653a29b9025d9d97d33d01cada3d4bbe616d2
