### ISSUE TITLE
about the mugration

### ISSUE THREAD

**Issue by bacterpang** [neherlab/treetime#268]
Hi, I got a problem running mugration.
[testfiles.zika.tar.gz](https://github.com/neherlab/treetime/files/14545548/testfiles.zika.tar.gz)

I download the zika data and try to run as below:
treetime mugration --tree zika.nwk --states zika.csv --attribute country --confidence --outdir out1

I got the results, however, there was something strange with the "confidence.csv" file. There are "ABCD...." in the first row and I don't know what do they mean.

I also attached the files I used. The Treetime version was 0.11.2.
Could anybody tell me what was wrong? Thanks.

**Comment by Azarian-Lab** [comment]
Hello! They are your locations. If you open the `GTR` file you will see what they are.

**Comment by bacterpang** [comment]
@Azarian-Lab Hi, thank you very very much! I found them. This confused me several days.
