### ISSUE TITLE
'branch_mutations.txt' output always empty (v 0.11.3)

### ISSUE THREAD

**Issue by LewisCEMason** [neherlab/treetime#272]
Dear Devs,

I hope that you are well.

I am using TreeTime (v 0.11.3), installed with `conda install bioconda::treetime`.

I am using the ancestral sequence reconstruction (with VCF files) command, `treetime ancestral --aln data/tb/lee_2015.vcf.gz --vcf-reference data/tb/tb_ref.fasta --tree data/tb/lee_2015.nwk` , (but with my own files) as a means to obtain the branch_mutations.txt output, but am finding that this output is always empty. The other outputs (ancestral_sequences.vcf, annotated_tree.nexus, auspice_tree.json, sequence_evolution_model.txt) are not empty. 

I am unsure of what is going on here, and was wondering if you could help?

**Comment by rneher** [comment]
thanks for alerting us of this. I have found the bug and it should be fixed with the next release.

**Comment by rneher** [comment]
https://github.com/neherlab/treetime/commit/52d7e9a509ab12e7e088d29975347a2618c047f1
