### ISSUE TITLE
_attach_sequences_to_nodes Called Twice In TreeAnc.py init

### ISSUE THREAD

**Issue by emmahodcroft** [neherlab/treetime#29]
In TreeAnc.py:

Inside of the init 'self.aln' is assigned in line 89, which called the 'setter' on line 241. Inside the setter, if a tree is attached, this calls _attach_sequences_to_nodes on line 254. 
Back in init, after 'self.aln' is assigned, if aln is not None, _attach_sequences_to_nodes is called on line 91

**Comment by rneher** [comment]
Thanks! fixed in c1a770ad405e4a5ca593f6144bb5e315cbff952a
