### ISSUE TITLE
No Treeanc module found 

### ISSUE THREAD

**Issue by OnlyHigh** [neherlab/treetime#32]
Hi, trying to run Treetime, i get the following error:

Traceback (most recent call last):
  File "/home/bio/treetime/ancestral_reconstruction.py", line 4, in <module>
    from treetime import TreeAnc, GTR
  File "/home/bio/treetime/treetime/__init__.py", line 1, in <module>
    from treeanc import TreeAnc
ModuleNotFoundError: No module named 'treeanc'

Could you please help me?,
Thanks in advance,
Luis Alfonso.

**Comment by alexjfortuna** [comment]
I am having the same issue, thank you.

**Comment by rneher** [comment]
Sorry about the late reply -- was traveling. Did you install treetime? Or are you simply running the script from within the folder?

**Comment by alexjfortuna** [comment]
Hi, I was able to get it to work indirectly by installing panX and source activate panX.

**Comment by rneher** [comment]
could it be that your default python is python3 outside of if the panX environment? The master branch of treetime requires python2.7. there is a py3 branch, but somewhat experimental as of now.

**Comment by rneher** [comment]
Thanks for letting me know. @OnlyHigh , does it work for you now?

best,
richard

**Comment by OnlyHigh** [comment]
Yes, 
It works, 
Thank you!,
Luis Alfonso.
