### ISSUE TITLE
terminal_count not declared before.

### ISSUE THREAD

**Issue by evogytis** [neherlab/treetime#34]
https://github.com/neherlab/treetime/blob/ced94a7f6651971d3b56ed1113d8979aa48d6ba5/mugration.py#L127

**Comment by rneher** [comment]
thanks, @evogytis . should be fixed in d867a4f92033de23289f9272555276b7ffeb56ff (but do update biopython, otherwise the nexus export is pretty useless). Will add some docs soon.
