### ISSUE TITLE
Dealing w/ dates of different granularity

### ISSUE THREAD

**Issue by phiweger** [neherlab/treetime#59]
Hi,

I really like treetime, but was wondering how to deal w/ dates of different granularity. For example, one sample might date to 2017-01-01 ("day resolution") while another only has 2016 ("year resolution") in its metadata. 

Scaling all dates to year resolution seems wasteful, but I don't know how to encode the year-only dates so as to not bias the analysis.

Thank you.

**Comment by emmahodcroft** [comment]
Dear Adrian,

We're very glad to hear you like treetime! For dates with 'year resolution' you should be able to encode these as '2016-XX-XX' alongside those samples with 'day resolution' (or 'month resolution' as 2017-01-XX). 

I hope this helps!

**Comment by phiweger** [comment]
Awesome I will give it a shot.
