### ISSUE TITLE
missing example data?

### ISSUE THREAD

**Issue by phiweger** [neherlab/treetime#62]
When cloning the repo it seems the example data is not pulled.

My (maybe stupid) question:

- Is there any example data meant to be distributed? (I read some references to it in the tutorials)
- If so, might the error be that you missed including the non-code data in a Manifest, see

https://python-packaging.readthedocs.io/en/latest/non-code-files.html

Thanks and best

**Comment by emmahodcroft** [comment]
Dear Adrian,

The example data can be found in a separate repo: https://github.com/neherlab/treetime_examples . Sorry about that confusion.

Hope that helps

**Comment by phiweger** [comment]
Perfect, thanks. Maybe link to it in the treetime README? Best.
