### ISSUE TITLE
question on rescaling

### ISSUE THREAD

**Issue by phiweger** [neherlab/treetime#63]
In the [homology tutorial](https://github.com/neherlab/treetime_examples/blob/master/homoplasy.md#vcf-input-and-reduced-alignments) it states that a rescaling is needed when working from a _variable position only alignment_ -- this is what I do.

However, as I am new to this type of analysis, I don't know what to use to rescale. The tutorial states `271/4411532=0.0000614` -- Is that the number of variable positions in the alignment (e.g. SNVs) divided by the length of genome of the reference?

Thank you.

**Comment by rneher** [comment]
Yes, if you build a tree from an alignment of variable positions only without correcting/adjusting branch lengths, the rescaling factor should be the number of variable positions divided by the length of the genome. 

The script only needs this factor to calculate an expectation of how many homoplasies to expect, the rest is pretty independent of this factor.

**Comment by phiweger** [comment]
Thank you for the quick reply!
