### ISSUE TITLE
treetime --confidence output

### ISSUE THREAD

**Issue by phiweger** [neherlab/treetime#64]
Hi,

Maybe I did overlook something: But is there a "textual" output of the confidence intervals calculated by `treetime ... --confidence`? 

If not, I think this would be a very useful feature.

Thank you.

**Comment by rneher** [comment]
the confidence intervals should be written into the `dates.tsv` as 
```
#Lower and upper bound delineate the 90% max posterior region
#node	date	numeric date	lower bound	upper bound
NODE_0000512	2010-02-08	2010.108044	2009.354947	2011.206138
NODE_0000462	2010-08-09	2010.606797	2009.970767	2011.540584
THA/2014/SV0127_14	2017-05-07	2017.350133	2015.941074	2019.089610
NODE_0000463	2011-06-26	2011.485768	2010.861316	2012.358705
...
```
As of 0.5.1, the confidence should also reflect rate uncertainty, either estimated from the root-to-tip vs date regression or specified via `--clock-std-dev`.

**Comment by phiweger** [comment]
aw, I knew I overlooked something, thank you

**Comment by virologist** [comment]
Hi,

I am trying to setup the --clock-std-dev parameter when I am doing the treetime(Linux).
However when give this parameter, it always pop out this error:
reetime: error: argument --clock-std-dev: expected one argument
**So, what kind of argument I should give to this set?**
the doc only showing "--clock-std-dev: standard deviation of the provided clock rate estimate", no more detail was found.

Thanks a lot

**Comment by rneher** [comment]
this expects a floating-point number. if your rate is for example 0.0001 +/- 0.00003 you would call it as 

`--clock-rate 0.0001 --clock-std-dev 0.00003`

hope this helps!
