### ISSUE TITLE
why I could not find ancestral_reconstruction.py?

### ISSUE THREAD

**Issue by lixingguang** [neherlab/treetime#67]
@rneher why I could not find ancestral_reconstruction.py?

**Comment by rneher** [comment]
The example scripts were moved into a separate repository:

https://github.com/neherlab/treetime_examples/tree/master/scripts

Furthermore, we exposed this functionality as a command line tool, see here for a usage example:

https://github.com/neherlab/treetime_examples/blob/master/ancestral.md
