### ISSUE TITLE
Can ancestral_reconstruction.py be used for amino acid sequences ?

### ISSUE THREAD

**Issue by lixingguang** [neherlab/treetime#68]
@rneher Can ancestral_reconstruction.py be used for amino acid sequences ?

**Comment by lixingguang** [comment]
I used amino acid sequences for mugration model, it showed nucleotide mutation, for example, A334G, not amino acid mutation?
<img width="140" alt="image" src="https://user-images.githubusercontent.com/10130954/48321717-ffef7e80-e65e-11e8-9d10-7776ae733592.png">

**Comment by rneher** [comment]
thanks for point this out. we had never really used the amino acid functionality and it was somewhat hidden and buggy, I cleaned this up a bit. If you update treetime to current master, amino acid reconstructions should work as described here:
https://github.com/neherlab/treetime_examples/blob/master/ancestral.md#amino-acid-sequences
