### ISSUE TITLE
what is the difference between marginal and joint ancestral reconstruction?

### ISSUE THREAD

**Issue by lixingguang** [neherlab/treetime#76]
@rneher what is the difference between marginal and joint ancestral reconstruction?
Could you please give me an example, thanks.

**Comment by rneher** [comment]
https://www.google.com/search?hl=en&q=marginal%20and%20joint%20ancestral%20reconstruction

**Comment by lixingguang** [comment]
@rneher thanks for your reply. 
could we cooperate with sequence data analysis, thanks. :)
