### ISSUE TITLE
root to tip regression and evolutionary rate estimate

### ISSUE THREAD

**Issue by baptelie** [neherlab/treetime#79]
Hi,
I'm trying to use tree time to build a time-aligned tree, but I get strange evolutionary rate estimates: 2e-3 instead of the 4e-3 expected. When I look at the root to tip regression, the regression doesn't seem to match the plot (see attached), and when I make a regression on excel from the rtt file I get my 4e-3.
[root_to_tip_regression.pdf](https://github.com/neherlab/treetime/files/2792533/root_to_tip_regression.pdf)
![rtt excel](https://user-images.githubusercontent.com/47003979/51691906-bbbb1b80-1fc9-11e9-9344-a7470bbe8b07.jpeg)
I run it directly as a command-line on Mac, if you need my data and my command please tell me.

Thanks,

**Comment by rneher** [comment]
yes, this seems wrong. would be great if you could pass on the tree/data for me to test and investigate.

**Comment by baptelie** [comment]
Of course, thank you !
[data.zip](https://github.com/neherlab/treetime/files/2799592/data.zip)

**Comment by rneher** [comment]
I think there are two issues here. You made this tree with fasttree, right? there are many branches of length 0.0005 which probably have length 0. this generates excess divergence. The other issue I can see is that these are very many (>5000) very similar HA sequences with lots of randomly resolved multifurcations. This will often put late sequences ahead of early sequences in the tree. This throws off treetime's default rooting/rate estimation mechanism that uses the tree structure to estimate covariance (and the fact flu evolution tends to be bursty doesn't help). For the time being, I'd suggest you rerun with `--reroot least-squares`. This should do a simple least-squares regression.

**Comment by rneher** [comment]
but thanks for sharing data and pointing this out!

**Comment by baptelie** [comment]
Thank you very much for your answer ! Yes, I used fast tree, and I then built a fully bifurcating tree for another purpose. So, using the initial tree from fast tree (i.e. containing multifurcations) and the parameter` --reroot least-squares` I obtained the expected root-to-tip correlation for `treetime clock`, but not when I use the general command `treetime`, with exactly the same parameters ... And actually the r^2 is better with the second correlation ! Do you have any idea of the reason ?
Thanks,
[root_to_tip_regression-treetimeclock.pdf](https://github.com/neherlab/treetime/files/2803820/root_to_tip_regression-treetimeclock.pdf)
[root_to_tip_regression-treetime.pdf](https://github.com/neherlab/treetime/files/2803822/root_to_tip_regression-treetime.pdf)

**Comment by rneher** [comment]
The reason that the regressions differ is that treetime will have re-optimized branch lengths and are resolved polytomies. Just doing least-squares on the tree from fasttree will give you a too high rate. But the treetime estimate is probably too low. I'll have to change the default behavior here slightly because it doesn't work well for big collections of very similar sequences.
