### ISSUE TITLE
Add inferred discrete traits to timetree

### ISSUE THREAD

**Issue by gkarthik** [neherlab/treetime#80]
Hello Richard,

I was trying to infer discrete traits(location) and add those traits to a time tree(inferred by treetime too) using the command line. The annotated_tree.nexus produced by "mugration" and the timetree.nexus produced don't seem to have the same topology(albeit with unresolved polytomies that I'm working on resolving now) despite using the same ML tree as input. Is there a way to do this apart from using treetime as a library? 

I was digging into [wrappers.py](https://github.com/neherlab/treetime/blob/8eb0a9c6e14d4184021b9d61f7cd85629e0a7fea/treetime/wrappers.py) but wanted to see if this was already done before going further. Thanks!

Best,
Karthik

**Comment by rneher** [comment]
Hello Karthik,

treetime attempts to resolve polytomies, which will change the number of internal nodes. You can use the output of treetime as input to the mugration model, they should then have identitical topology. I can add an argument to the CLI to not resolve polytomies if this helps. 

beset,
richard

ps: the rate estimation seems to behave a little oddly on trees with very many polytomies. I might have to change the default behavior here.

**Comment by gkarthik** [comment]
Thank you for the quick response! I’ll use the timetree as input. 
The CLI already has the flag —keep-polytomies. Is that the argument you’re referring to?

The data I’m looking at is for West Nile virus. Treetime converges in 5 iterations but some of the polytomies remain unresolved. For example, on [NextStrain](
https://nextstrain.org/WNV/NA) the clade with sequence W711.

**Comment by rneher** [comment]
Yes, the --keep-polytomies argument is what I was referring to. I had forgotten I already did that.

that some polytomies remain unresolved is not unexpected. The resolution is largely restricted to "pulling cherries out of the polytomy"  when this improves the likelihood.
