### ISSUE TITLE
Polytomies in output tree?

### ISSUE THREAD

**Issue by cizydorczyk** [neherlab/treetime#81]
Hello,

I am trying to run TimeTree on a bacterial dataset. I successfully run it with a relaxed clock model (--relax 1.0 0.5), but I end up with 2 polytomies, each consisting of 3 isolates, in my final tree (timetree.pdf file).

Why would polytomies appear in the final tree? Could this be a sign of something not being right in the analysis/with the input data? The data is moderately clock-like (r^2 = ~0.57), but I figured this would be okay for a relaxed clock approach...the polytomies in question have a minimum distance of 2 SNPs between the closest 2 isolates, and 4-6 SNPs between the most distant two, so no two isolates are identical and under a standard ML phylogenetic approach, no polytomies are formed...

I have also tried running it without the "--relax" option (strict clock?) and the polytomes remain.

Any help in understanding why this might be occurring would be greatly appreciated.

Thank you,
Conrad Izydorczyk

**Comment by rneher** [comment]
Hi Conrad,

TreeTime doesn't necessarily resolve all polytomies and it is not unexpected that some remain. The polytomies you refer to, are these deep in the tree or involved terminal branches? No two isolates being identical doesn't guard against polytomies. More than two taxa can descent from an identical ancestor without being identical to each other. 

hope this helps, let me know if not.
richard

**Comment by cizydorczyk** [comment]
Hi Richard,

Thank you for your response. Yes, that clears it up. The polytomies I refer to occur immediately ancestral to a few tips of the tree. They are generally closely related (<4 SNPs).
