### ISSUE TITLE
Feature request; turn off outlier identification

### ISSUE THREAD

**Issue by TimHHH** [neherlab/treetime#84]
Hi there.
I am looking at a number of stats (particularly R^2) for closely related datasets (alignments in/excluding regions of interest), but different outliers are identified and subsequently ignored for each dataset. Could I please request an option to turn off the outlier identification so that I can directly compare the stats for such datasets?
Thanks.
Tim

**Comment by rneher** [comment]
this should be already in place. run it with `--clock-filter 0`

**Comment by TimHHH** [comment]
great, thanks.
