### ISSUE TITLE
Question about --clock-rate and --relax behavior

### ISSUE THREAD

**Issue by cizydorczyk** [neherlab/treetime#85]
Hi Richard,

I have a couple of questions regarding the behaviour of the `--clock-rate` and `--relax` options I was hoping you could answer.

1) As I understand it, using the `--clock-rate` option specifies a single rate for the entire tree, which is equivalent to fitting a strict clock to the data but without estimating the rate - is that correct? Does not specifying the` --relax` option then mean a strict clock is estimated from the data?

2) If the above is true, then I assume the `--relax` option uses an auto-correlated relaxed clock instead. Is it possible to use the two options together? As in, specify a clock rate (median, average, etc.) and fit a relaxed clock to the data such that the specified rate is used as a guide for fitting the relaxed clock? Or does one option supersede the other and either a fixed rate is used or a relaxed clock fitted, but not both?

Any help is greatly appreciated.

Thank you,
Conrad

**Comment by rneher** [comment]
Sorry about the late reply. regarding your first point:
 
Yes, specifying clockrate specifies a single rate for the entire tree. If you run with `--relax`, TreeTime will estimate a rate from data (essentially the root to tip regression) and then allow variation around this estimate along the branches of the tree. 

regarding your second point:
If on top of that you specify relax, it will allow fluctuations around the mean rate you specified. But I don't think I ever tested this.
