### ISSUE TITLE
Adding a Newick File

### ISSUE THREAD

**Issue by noahaus** [neherlab/treetime#91]
Hello,

Simple question, but I just wanted to know if optionally adding a tree file with TreeTime helps speeds up analysis? If not, what does the optional tree file help assist the program in doing?

Best, and thank you in advance

**Comment by rneher** [comment]
you can give TreeTime a tree with the `--tree <treefile.nwk>` flag. In this case it will use this tree for the overall topology and doesn't infer one using iq-tree, raxml or fasttree.
