### ISSUE TITLE
wrappers.py 

### ISSUE THREAD

**Issue by cmavian** [neherlab/treetime#92]
Hi, 

I am trying to use the mugration function and I am getting this error: 

  File "/Users/nartuhi/miniconda3/bin/treetime", line 12, in <module>
    return_code = params.func(params)
  File "/Users/nartuhi/miniconda3/lib/python3.7/site-packages/treetime/wrappers.py", line 761, in mugration
    pc=params.pc, sampling_bias_correction=params.sampling_bias_correction, verbose=params.verbose)
  File "/Users/nartuhi/miniconda3/lib/python3.7/site-packages/treetime/wrappers.py", line 664, in reconstruct_discrete_traits
    unique_states = sorted(set(traits.values()))
TypeError: '<' not supported between instances of 'str' and 'float'

I have checked my files, and I do not have such character within the attribute nor the nwk, I tried example files and they work thought. 
I do not understand what I should do to fix the error. 

Can you help me please?

Thank you very much

Carla

**Comment by cmavian** [comment]
please close the issue: the problem was that I used 'NA' to assign unknown location, however pandas was recognizing it as 'nan' so a number. I changed it to 'UNKNOWN' and worked! :)

**Comment by rneher** [comment]
thanks for looking into it. I'll put in a check for consistent type when reading metadata. This has been a problem before.

**Comment by cmavian** [comment]
No problem! I was trying to understand where the problem was in my metadata, wasn’t apparent at first.. but after some digging :)


Carla Mavian, Ph.D., MSc
Postdoc Associate
TH Maren Awardee
Salemi Lab
Data Intelligence Systems Lab
Emerging Pathogens Institute
OneHealth Center of Excellence
Department of Pathology
College of Medicine
University of Florida
Gainesville, FL, 32610
Room 200F
352-273-9419


On Sep 29, 2019, at 4:22 PM, Richard Neher <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL EMAIL: Exercise caution with links and attachments.




thanks for looking into it. I'll put in a check for consistent type when reading metadata. This has been a problem before.
