### ISSUE TITLE
Add --version to all tools

### ISSUE THREAD

**Issue by tseemann** [neherlab/treetime#93]
It would be helpful for packaging to have this to stdout and return error code 0.
```
% treetime --version
treetime 0.6.3
```
Easy to do with `argparse`:
```
parser.add_argument("--version", action="version", version="%(prog)s " + __version__)
```

**Comment by rneher** [comment]
thanks, Torsten. I added the `--version` argument here in 67db41bd308c1da81683cc49971a5c0a89cf8be7

There was/is a `treetime version` subcommand. this now also prints "treetime 0.6.3" rather than just "0.6.3".

**Comment by tseemann** [comment]
Oh sorry @rneher I didn't notice the `version` subcommand!
