### ISSUE TITLE
Plotting and/or viewing annotated nexus tree

### ISSUE THREAD

**Issue by taylorpaisie** [neherlab/treetime#94]
Hi Richard,

I ran the "treetime mugration" command on my data and received the annotated nexus tree output with no problems.  Due to the specific way you annotate this nexus file (for example [&country="brazil"]), is there a way to convert this file to a nexus file that can be opened in any of the various tree viewers?  Thanks!

Taylor

**Comment by rneher** [comment]
Hi Taylor,
I am not sure what you mean. If I open these nexus tree in FigTree, the annotations are parsed correctly and can be used to annotate the tree. What do you think the annotations should look like?
best,
richard

**Comment by taylorpaisie** [comment]
Hi Richard,

It wasn't working when I tried opening in FigTree or iTOL, but I did get it to work using IcyTree.  hmmm strange, I'll have to try it with another data set of mine and see what happens.  Thanks for the response!

Taylor
